# Use new container infrastructure to enable caching
sudo: requires

# Choose a lightweight base image; we provide our own build tools.
language: generic

services:
  - docker

before_install:
  - sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.10.0/docker-compose-$(uname -s)-$(uname -m)"
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo mkdir /mnt/docker

script:
  - make
