resolver: lts-6.2
packages:
- '.'
- location:
    git: https://github.com/abailly/system-extra
    commit: bbb78d47462a24f3bcfc2bab0ac080370262ea49
  extra-dep: true

extra-deps:
  - amazonka-core-1.4.3
  - amazonka-1.4.3
  - amazonka-apigateway-1.4.3
  - amazonka-lambda-1.4.3
  - tokenize-0.3.0
